image: docker

services:
  - docker:dind

stages:
  - build
  - test
  - deploy


build:
  stage: build
  image: docker:git
  interruptible: true
  only:
    - main
  services:
    - docker:dind
  script:
      - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $CI_REGISTRY_IMAGE --pull .
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker push $CI_REGISTRY_IMAGE

deploy:
  image: alpine
  stage: deploy
  environment: production
  only:
    - main
  tags:
    - ccb
  before_script:
    - apk add --no-cache openssh
    - eval "$(ssh-agent -s)"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh/
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - ssh root@deflector.cs.hhu.de


sast:
  stage: test
  interruptible: true
include:
  - template: Security/SAST.gitlab-ci.yml
